FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"

SRC_URI += "\
    file://0001-glupload-Only-offer-DMABuf-caps-feature-if-using-EGL.patch \
    file://0002-gl-gbm-allow-headless-mode.patch \
    file://0003-gst-libs-include-config.h-in-all-source-files.patch \
    file://0004-glmemory-Fix-n_wrapped_pointers-usage.patch \
    file://0005-gl-egl-Add-gst_egl_image_from_dmabuf_direct-function.patch \
    file://0006-glupload-try-to-use-the-last-method-after-reconfigur.patch \
    file://0007-glupload-allow-system-memory-for-dmabuf-in-transform.patch \
    file://0008-glupload-handle-upload-methods-with-different-caps.patch \
    file://0009-gluploadelement-try-to-avoid-dropping-buffers.patch \
    file://0010-glupload-Implement-direct-dmabuf-uploader.patch \
    file://0011-glupload-calculate-DRM-fourcc-once-for-direct-dmabuf.patch \
    file://0012-glupload-debug-output-from-dmabuf-and-dmabuf_direct-.patch \
    file://0013-glupload-dmabuf-direct-query-formats-before-modifier.patch \
    file://0014-glupload-dmabuf-direct-report-driver-limitations-to-.patch \
    file://0015-glupload-Do-prepend-the-preferred-caps.patch \
    file://0016-gl-egl-Determine-correct-format-on-dmabuf-import.patch \
    file://0017-glupload-dmabuf-be-explicit-about-gl-formats-used.patch \
    file://0018-opengl-gbm-Adds-missing-unrefs-for-gl-context-and-dr.patch \
    file://0019-gst-gl-Remove-duplicate-declarations.patch \
    file://0020-gl-gbm-Improve-logging-output.patch \
    file://0021-gl-gbm-Add-GST_GL_GBM_DRM_CONNECTOR-environment-vari.patch \
    file://0022-gl-window-gbm-Remove-unneeded-extra-function.patch \
    file://0023-gl-window-gbm-Remove-unused-private-class-member.patch \
    file://0024-gl-window-gbm-Restore-CRTC-on-close.patch \
    file://0025-glupload-dmabuf-use-out_info-to-create-allocation-pa.patch \
    file://0026-glupload-Don-t-leak-caps-features.patch \
    file://0027-gl-fix-a-few-other-leaks-when-not-getting-to-PAUSED.patch \
    file://0028-gl-Don-t-restore-the-viewport-on-function-exit.patch \
    file://0029-gluploadelement-Fix-caps-leak.patch \
    file://0030-glupload-prevent-segfault-when-updating-caps.patch \
    file://0031-glupload-Keep-track-of-cached-EGLImage-texture-forma.patch \
    file://0032-eglimage-Fix-memory-leak.patch \
    file://0033-glimagesink-fix-upper-left-and-upper-right-rotate-ma.patch \
    file://0034-gl-egl-support-direct-dmabuf-import-with-external-oe.patch \
    file://0035-gl-gbm-ensure-we-call-the-resize-callback-before-att.patch \
    file://0036-glupload-dmabuf-support-direct-upload-into-external-.patch \
    file://0037-glupload-fix-transform_caps-NULL-pointer-dereference.patch \
    file://0038-glupload-dmabuf-add-DirectDmabufExternal-uploader.patch \
    file://0039-glupload-dmabuf-only-accept-uploads-to-external-oes-.patch \
    file://0040-video-Add-NV12_10LE40-pixel-format.patch \
    file://0041-playbin3-Fix-qt-videoplayer-cannot-change-video-stat.patch \
    file://0042-playbin2-Add-preferred-audio-video-sink.patch \
    file://0043-HACK-xvimagesink-Support-dma-buffer-rendering.patch \
    file://0044-video-converter-Support-rockchip-RGA-2D-accel.patch \
    file://0045-HACK-gl-egl-allow-direct-dmabuf-import-when-unable-t.patch \
    file://0046-glupload-dmabuf-prefer-DirectDmabufExternal-uploader.patch \
    "
