# Copyright (C) 2017 Romain Perier
# Copyright (C) 2017 Eddie Cai
# Released under the MIT license (see COPYING.MIT for the terms)

require recipes-kernel/linux/linux-yocto.inc

SRC_URI = "git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
SRC_URI += " \
	file://rockchip.cfg \
"
# FROMLIST PATCH
SRC_URI += " \
	file://v4-1-5-dt-bindings-gpu-add-bindings-for-the-ARM-Mali-Midgard-GPU.patch \
	file://v4-2-5-ARM-dts-rockchip-add-ARM-Mali-GPU-node-for-rk3288.patch \
	file://v4-3-5-ARM-dts-rockchip-enable-ARM-Mali-GPU-on-rk3288-rock2-som.patch \
	file://v4-4-5-ARM-dts-rockchip-enable-ARM-Mali-GPU-on-rk3288-firefly.patch \
	file://v4-5-5-ARM-dts-rockchip-enable-ARM-Mali-GPU-on-rk3288-veyron.patch \
	file://03-41-drm-rockchip-support-prime-import-sg-table.patch \
	file://1-5-media-rockchip-rga-v4l2-m2m-support.patch \
	file://2-5-ARM-dts-rockchip-add-RGA-device-node-for-RK3288.patch \
	file://3-5-ARM-dts-rockchip-add-RGA-device-node-for-RK3399.patch \
	file://4-5-ARM-dts-rockchip-enable-RGA-for-rk3288-devices.patch \
	file://5-5-dt-bindings-Document-the-Rockchip-RGA-bindings.patch \
"

# FROMLIST + NO-REPLY PATCH
SRC_URI += " \
	file://0013-clk-rockchip-rk3288-prefer-vdpu-for-vcodec-clock-sou.patch \
	file://soc-rockchip-power-domain-export-idle-request.patch \
	file://v5-8-8-iommu-rockchip-Enable-Rockchip-IOMMU-on-ARM64.patch \
"

SRC_URI += " \
	file://arm-dts-add-missing-node-in-upstream.patch \
	file://arm-dts-add-rga-gpu-vpu-for-rk3288-evb.patch \
	file://ARM-dts-rockchip-enable-gpu-and-vpu-for-RK3288-Tinke.patch \
	file://v6-3-3-drm-rockchip-Support-10-bits-yuv-format-in-vop.patch \
	file://v6-1-3-drm_fourcc-Add-new-P010-P016-video-format.patch \
	file://0001-drm-skip-permit-check.patch \
"

SRCREV = "c0bc126f97fb929b3ae02c1c62322645d70eb408"
LINUX_VERSION = "4.12"
# Override local version in order to use the one generated by linux build system
# And not "yocto-standard"
LINUX_VERSION_EXTENSION = ""
PR = "r1"
PV = "${LINUX_VERSION}-rc7"

# Include only supported boards for now
COMPATIBLE_MACHINE = "(rk3036|rk3288|rk3328|rk3399)"

KCONFIG_MODE = "--alldefconfig"
